apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: tanzupartnerdemo
spec:
  title: Tanzu Service Mesh Workshop
  description: Workshop created to demo the workload creation in TKG
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/dineshtripathi30/tanzupartnerdemo
  content:
     files: github.com/dineshtripathi30/tanzupartnerdemo?ref=main?ref=main
     image: docker.io/eknath009/lcimagewithoutaz:newest
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
